# Generated by Django 5.2.7 on 2025-10-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='clientes/'),
        ),
    ]
